Repository glue-viz/glue-jupyter, pull requests merged in 2022-10, with the labels that each got.

#321 Setup automated changelog generation for release process
  .github/release.yml
  .github/workflows/update-changelog.yaml
  CHANGES.md
  CHANGES.rst
  RELEASE.rst
  RELEASE_INSTRUCTIONS.md
Labels: no-changelog-entry-needed

#322 Add rules for labels to be skipped in changelog
  .github/release.yml
  CHANGES.md
Labels: priority-medium, no-changelog-entry-needed

#323 Changelog skips and full diff links
  .github/release.yml
  CHANGES.md
Labels: documentation, no-changelog-entry-needed

#327 Fix support for all BaseCartesianData subclass instances
  glue_jupyter/state_traitlets_helpers.py
  glue_jupyter/utils.py
Labels: bug

#326 Fix IndexError that occurred in some cases during JSON to State translation
  glue_jupyter/state_traitlets_helpers.py
  glue_jupyter/tests/test_state_traitlets_helpers.py
Labels: bug

#328 Autorelease updates
  CHANGES.md
  README.rst
  RELEASE_INSTRUCTIONS.md
Labels: documentation, no-changelog-entry-needed

#329 Updated dependencies to run and test with Python 3.11
  .github/workflows/ci_workflows.yml
  MANIFEST.in
  setup.cfg
  tox.ini
Labels: testing

#330 ReStructure Release Instructions
  RELEASE.rst
Labels: documentation, no-changelog-entry-needed
